# Site settings
title: Joost VanderBorgh's Portfolio
description: 
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "https://joostvan.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joost VanderBorgh
user_description: 
user_title: Computational Physics @ UPenn
email: jvanderborgh@gmail.com
twitter_username: lorem_ipsum
github_username:  joostvan
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
